// src/debug-modal.js (Final, Refined Version)

import { generatePrompts } from './prompts.js';
import { LINGUISTIC_STYLES, DATE_ARC_PHASES } from './conversationHelpers.js';
import {
    setNestedValue,
    createSelect,
    createMultiSelect,
    createTextarea,
    createInput,
    createCheckbox,
    createSlider,
    createCollapsibleJSON,
    createAnalysisView
} from './ui-components.js';

/** @type {import('./conversationHelpers.js').GenerationData} */
let modalState = {};
let callbacks = {};
let currentView = 'analysis'; // Start at the new first view
const VIEWS = ['analysis', 'context', 'final'];

const CONVERSATION_STATES = ['OPENER', 'EARLY_CONVO', 'ACTIVE_CONVO', 'REENGAGING_DAY', 'REENGAGING_WEEK', 'REENGAGING_MONTH'];
const INTENT_OPTIONS = ['questioning', 'planning', 'reacting_to_humor', 'storytelling', 'flirting_or_sexual'];

// --- View Rendering Logic ---
function renderView() {
    const contentEl = document.getElementById('debug-modal-content');
    if (!contentEl)
        return;

    let html = '';
    switch (currentView) {
    case 'analysis':
        html = renderAnalysisView();
        break;
    case 'context':
        html = renderContextView();
        break;
    case 'final':
        html = renderFinalPayloadView();
        break;
    }
    contentEl.innerHTML = html;
    attachEventListeners();
}

function renderAnalysisView() {
    const analysis = modalState.conversationAnalysis || {};
    const fallbackKeys = analysis.fallbackKeys || [];
    const constants = { CONVERSATION_STATES, INTENT_OPTIONS, DATE_ARC_PHASES };
    const { analysisHtml, memoryHtml } = createAnalysisView(analysis, fallbackKeys, constants);

    return `
        <h3>View 1: Conversation Analysis</h3>
        <p>This is the analysis generated by the background script. You can override these values before generating the final prompt.</p>
        ${analysisHtml}
        ${memoryHtml}
        ${createCollapsibleJSON('View/Edit Raw Analysis', analysis, true, 'analysis')}
    `;
}

function renderContextView() {
    const { conversationHistory } = modalState;
    const historyHtml = conversationHistory.map((msg, index) => `
        <div class="message-card" data-index="${index}">
            <div class="message-card-header">
                <select class="modal-input" data-path="conversationHistory.${index}.role">
                    <option value="user" ${msg.role === 'user' ? 'selected' : ''}>User</option>
                    <option value="assistant" ${msg.role === 'assistant' ? 'selected' : ''}>Assistant</option>
                </select>
                <button class="icon-btn remove-msg-btn" title="Remove Message">&times;</button>
            </div>
            <div class="message-card-content">
                <textarea class="modal-input" data-path="conversationHistory.${index}.content">${msg.content}</textarea>
            </div>
        </div>
    `).join('');

    return `
        <h3>View 2: Profiles & History</h3>
        <table class="payload-table">
            <tr><td>My Name</td><td>${createInput('context-myName', 'myName', modalState.myName)}</td></tr>
            <tr><td>Their Name</td><td>${createInput('context-theirName', 'theirName', modalState.theirName)}</td></tr>
            <tr><td>My Profile</td><td>${createTextarea('context-myProfile', 'myProfile', modalState.myProfile)}</td></tr>
            <tr><td>Their Profile</td><td>${createTextarea('context-theirProfile', 'theirProfile', modalState.theirProfile)}</td></tr>
            <tr><td>Force Geo-Context?</td><td>${createCheckbox('context-forceIncludeGeoContext', 'forceIncludeGeoContext', modalState.forceIncludeGeoContext)}</td></tr>
        </table>
        <h4>Conversation History</h4>
        <div class="messages-container">${historyHtml}</div>
        <button id="add-message-btn" class="btn btn-secondary add-message-btn">Add Message</button>
        ${createCollapsibleJSON('View/Edit Raw GeoContext Data', modalState.geoContextData)}
    `;
}

function renderFinalPayloadView() {
    const { systemMessage, userMessage } = generatePrompts(modalState);
    const finalPayload = {
        messages: [{
                role: "system",
                content: systemMessage
            }, {
                role: "user",
                content: userMessage
            }
        ],
        temperature: modalState.taskInstructions.temperature,
        top_p: modalState.taskInstructions.top_p
    };
    modalState.finalPayload = finalPayload;

    return `
        <h3>View 3: Final Payload Review</h3>
        <p>This is the exact data that will be sent to the AI. You can make final edits to the messages below.</p>
        <div class="messages-container">
            <div class="message-card">
                <div class="message-card-header"><strong>System Message</strong></div>
                <div class="message-card-content">${createTextarea('final-system', 'finalPayload.messages.0.content', systemMessage)}</div>
            </div>
            <div class="message-card">
                <div class="message-card-header"><strong>User Message</strong></div>
                <div class="message-card-content">${createTextarea('final-user', 'finalPayload.messages.1.content', userMessage)}</div>
            </div>
        </div>
        ${createCollapsibleJSON('View/Edit Raw Final Payload', finalPayload, false)}
    `;
}

// --- State Management & Event Handling ---
function updateStateFromUI(e) {
    const el = e.target;
    const path = el.dataset.path;
    if (!path)
        return;

    let value;
    if (el.type === 'checkbox') {
        value = el.checked;
    } else if (el.type === 'range' || el.type === 'number') {
        value = parseFloat(el.value);
    } else if (el.multiple) {
        value = Array.from(el.selectedOptions).map(opt => opt.value);
    } else {
        value = el.value;
    }

    if (path.endsWith('insideJokes') || path.endsWith('avoidedTopics') || path.endsWith('questionHistory')) {
        value = el.value.split('\n').filter(Boolean);
    }

    setNestedValue(modalState, path, value);

    const objectKey = path.split('.')[0];
    if (objectKey === 'conversationAnalysis') {
        updateRawJsonDisplay('analysis');
        if (path.includes('memory')) {
            updateRawJsonDisplay('memory');
        }
    } else if (objectKey === 'finalPayload') {
        updateRawJsonDisplay('final');
    }
}

function updateRawJsonDisplay(key) {
    const pre = document.querySelector(`.raw-json-area[data-object-key="${key}"]`);
    if (!pre)
        return;

    let objectToDisplay;
    switch (key) {
    case 'analysis':
        objectToDisplay = modalState.conversationAnalysis;
        break;
    case 'memory':
        objectToDisplay = modalState.conversationAnalysis.memory;
        break;
    case 'geocontext':
        objectToDisplay = modalState.geoContextData;
        break;
    case 'final':
        objectToDisplay = modalState.finalPayload;
        break;
    default:
        return;
    }
    pre.textContent = JSON.stringify(objectToDisplay, null, 2);
}

function attachEventListeners() {
    const contentEl = document.getElementById('debug-modal-content');
    contentEl.addEventListener('input', updateStateFromUI);
    contentEl.addEventListener('change', updateStateFromUI);

    // FIX: Attach event listener for sliders programmatically
    contentEl.querySelectorAll('input[type="range"][data-label-map]').forEach(slider => {
        slider.addEventListener('input', (e) => {
            const targetSlider = e.currentTarget;
            const valueDisplay = document.getElementById(`${targetSlider.id}-value`);
            if (valueDisplay) {
                const labelMap = JSON.parse(targetSlider.dataset.labelMap);
                const currentValue = targetSlider.value;
                const getLabel = (val) => {
                    const numVal = parseFloat(val);
                    for (const [limit, label] of Object.entries(labelMap)) {
                        if (numVal >= parseFloat(limit)) return label;
                    }
                    return Object.values(labelMap)[0];
                };
                valueDisplay.textContent = `${currentValue} (${getLabel(currentValue)})`;
            }
        });
    });

    document.querySelectorAll('.copy-json-btn').forEach(btn => {
        btn.addEventListener('click', e => {
            const button = e.currentTarget;
            const container = button.closest('.collapsible-json-container');
            if (!container)
                return;

            const pre = container.querySelector('pre.raw-json-area');
            if (!pre)
                return;

            const textToCopy = pre.textContent.replace(/\\n/g, '\n');

            navigator.clipboard.writeText(textToCopy);

            const originalIcon = button.innerHTML;
            button.innerHTML = '✅';
            button.disabled = true;
            setTimeout(() => {
                button.innerHTML = originalIcon;
                button.disabled = false;
            }, 1500);
        });
    });

    document.querySelectorAll('.raw-json-area[contenteditable="true"]').forEach(area => {
        area.addEventListener('blur', e => {
            try {
                const newJson = JSON.parse(e.target.textContent);
                const key = e.target.dataset.objectKey;
                if (key === 'memory') {
                    modalState.conversationAnalysis.memory = newJson;
                } else if (key === 'analysis') {
                    modalState.conversationAnalysis = newJson;
                } else {
                    modalState[key] = newJson;
                }
                renderView();
            } catch (err) {
                console.error("Invalid JSON entered:", err);
                e.target.style.border = '1px solid red';
            }
        });
        area.addEventListener('focus', e => {
            e.target.style.border = '';
        });
    });

    if (currentView === 'context') {
        document.getElementById('add-message-btn')?.addEventListener('click', () => {
            modalState.conversationHistory.push({
                role: 'user',
                content: '',
                date: new Date().toISOString().split('T')[0]
            });
            renderView();
        });
        document.querySelectorAll('.remove-msg-btn').forEach(btn => {
            btn.addEventListener('click', e => {
                const index = e.currentTarget.closest('.message-card').dataset.index;
                modalState.conversationHistory.splice(index, 1);
                renderView();
            });
        });
    }
}

// --- Main Modal Functions ---
function handleNav(direction) {
    const currentIndex = VIEWS.indexOf(currentView);
    let nextIndex = currentIndex + direction;
    if (nextIndex < 0 || nextIndex >= VIEWS.length)
        return;
    currentView = VIEWS[nextIndex];
    renderView();
    updateNavButtons();
}

function updateNavButtons() {
    const currentIndex = VIEWS.indexOf(currentView);
    document.getElementById('modal-back-btn').disabled = currentIndex === 0;

    const primaryBtn = document.getElementById('modal-primary-action-btn');
    primaryBtn.textContent = (currentIndex === VIEWS.length - 1) ? 'Send to AI' : 'Next';
}

/**
 * @param {import('./conversationHelpers.js').GenerationData} initialData
 * @param {object} cbs
 */
export function showNlpModal(initialData, cbs) {
    callbacks = cbs;
    modalState = JSON.parse(JSON.stringify(initialData));
    currentView = 'analysis';

    const overlay = document.getElementById('debug-modal-overlay');
    overlay.innerHTML = `
        <div class="modal">
            <div class="modal-header">Debug & Override Mode</div>
            <div class="modal-content" id="debug-modal-content"></div>
            <div class="modal-footer">
                <div class="modal-actions">
                    <button id="modal-cancel-btn" class="btn btn-secondary">Cancel</button>
                    <button id="modal-back-btn" class="btn btn-secondary">Back</button>
                    <button id="modal-primary-action-btn" class="btn btn-primary">Next</button>
                </div>
            </div>
        </div>
    `;
    overlay.classList.remove('hidden');

    document.getElementById('modal-cancel-btn').addEventListener('click', callbacks.hideDebugModal);
    document.getElementById('modal-back-btn').addEventListener('click', () => handleNav(-1));
    document.getElementById('modal-primary-action-btn').addEventListener('click', () => {
        if (currentView === 'final') {
            callbacks.setUIGeneratingState(true);
            callbacks.startTimer(Date.now());
            callbacks.hideDebugModal();
            callbacks.sendFinalPayloadToAI(modalState.finalPayload);
        } else {
            handleNav(1);
        }
    });

    renderView();
    updateNavButtons();
}

export function hideDebugModal() {
    const overlay = document.getElementById('debug-modal-overlay');
    if (overlay) {
        overlay.classList.add('hidden');
        overlay.innerHTML = '';
    }
}